### ISSUE TITLE
FDSC 1.4.1 Bug: "False Positive" attempts without API key open MetaSmoke site for getting the key, but not the "Enter Code" window.

### ISSUE THREAD

**Issue by teward** [Charcoal-SE/Userscripts#10]
We initially reverted in 1.3.1 because we couldn't auth with 1.2.x.  With 1.4.1, the auth issue is fixed... for typical flagging of a post.  However, when "False Positive" is selected, and no API key / write token is stored, the MetaSmoke API page where you can authorize the application is displayed, but the prompt window for entering the API code from that MetaSmoke page does not show up.

It shows up for no-write-token *flagging*, but not "false positive" recording.

**Comment by angussidney** [comment]
I think the code which closes the flag dialog after the false positive button is pressed is accidentally closing the input dialog too. Hopefully that should fix it.

**Comment by ArtOfCode-** [comment]
@angussidney that's what the afterFlag param is for

**Comment by teward** [comment]
@angussidney @ArtOfCode- Neither of you bumped the version with the change - the updates aren't getting grabbed as such...
