### ISSUE TITLE
FIRE: Refuse to flag if the user has more than 10% rejected/retracted spam flags on that site

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/userscripts#109]
See https://chat.stackexchange.com/transcript/message/43236347#43236347 for context

I'm suggesting that FIRE, our most used tool should refuse to automatically flag posts if the users declined/retracted spam flag ratio is higher than a safe 10% if the user has more than 10 flags for that site (so about 1 bad flag for every 9 good ones) (could be made more strict, but I think that would be a safe initial limit)

The reason I;m suggesting to do this from FIRE, instead of making moderators send mod messages, is the fact that silently failing to submit a flag, with a notification containing a message to the user that he should flag the post manually is more effective against the robo reviewer flaggers

I'm also suggesting that we put the limit under the settings of FIRE, so if the check starts acting up (or there is someone new who has made a few mistakes in the past, but is good now) it can be bypassed without having said person change the source of the script directly, and effectively locking him out of future updates

**Comment by Cerbrus** [comment]
The flag ratio is data that's not accessible from Stack Exchange's API, not even when a user is authorized.  
The way the global flag summary script obtains the ratio, is by _scraping_ every single site's "flags" page, for that user.

That's something I'm not willing to implement in FIRE.
