### ISSUE TITLE
SPAM: Modify it to work in Tavern on the Meta

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/userscripts#110]
My most active room in the chat network is Tavern on the Meta. I'm interested in the Smokey Pings After Message user script, but noticed that it only works on CHQ and SOCVR. Please modify it so it works on Tavern on the Meta as well.

**Comment by CalvT** [comment]
Done. I didn't increase the version number, so if you have it installed already you'll have to reinstall it.

**Comment by ArtOfCode-** [comment]
I bumped version to 0.2.1.

**Comment by SulphurDioxide** [comment]
Nice one, thanks all :)
