### ISSUE TITLE
Inconsistency in FIRE doco: README.md hotkeys 1-4 or 1-5?

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/userscripts#117]
The overview section says 1-4 selects buttons and 5 opens the post, but further down on the page, the individual "how to accomplish X" examples all seem to think there are 5 buttons and that 6 will open the post.  It seems the beginning is correct, but I'm submitting a bug report so that others who understand this stuff perhaps can sort out the discrepancy based on actual understanding of how it's supposed to work.

**Comment by makyen** [comment]
I've updated the docs significantly to reflect the addition of R/A flagging. I believe that this is resolved.
