### ISSUE TITLE
SIM: No way to close the dialog

### ISSUE THREAD

**Issue by spacemonaut** [Charcoal-SE/userscripts#123]
Once I open the SIM dialog, I can't close it. There's no X and I can't click outside it. I just have to refresh or something.

**Comment by ArtOfCode-** [comment]
norepro: clicking out should close it (and does for me)

**Comment by spacemonaut** [comment]
Looks like a collision between this and [Helpful Moderator Userscripts](https://github.com/mattlunn/so-mod). Not sure why.
