### ISSUE TITLE
FIRE forgets to escape HTML special characters before rendering

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/userscripts#141]
![image](https://user-images.githubusercontent.com/7273074/51434610-1ee24080-1ca0-11e9-8951-38dc0c37de38.png)

while the actual [post](https://metasmoke.erwaysoftware.com/post/155096) is caught for:

    Body - Position 0-12: <p><a href="
                          ^^^^^

**Comment by makyen** [comment]
Resolved in FIRE version 1.4.0, PR #180.
