### ISSUE TITLE
FIRE doesn't escape button elements in code blocks

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/userscripts#148]
Inside the code blocks of [this post which was caught by SD](https://metasmoke.erwaysoftware.com/post/179859), there are several `<button>` elements. However, when you open the post in FIRE, the HTML is rendered as an actual button:

![button elements are rendered as actual buttons](https://user-images.githubusercontent.com/4848802/58878619-36f0b480-86c3-11e9-92dd-9d0cee6266a5.png)

**Comment by angussidney** [comment]
Another example in the wild: https://metasmoke.erwaysoftware.com/post/189210

**Comment by makyen** [comment]
Resolved in #180 (FIRE version 1.4.0)
