### ISSUE TITLE
FDSC1.8.3 ReferenceError after metasmoke authentication

### ISSUE THREAD

**Issue by unarist** [Charcoal-SE/Userscripts#18]
```
VM2548:249 fdsc.msWriteToken:  null
VM2548:80 getWriteToken
VM2548:85 input callback: ***
VM2548:131 sendFeedback
VM2548:132 fdsc.msWriteToken:  ***
VM2548:154 Array(3)
VM2548:155 Uncaught ReferenceError: nodeEvent is not defined
    at Object.<anonymous> (<anonymous>:155:19)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at y (jquery.min.js:4)
    at XMLHttpRequest.c (jquery.min.js:4)
```

`VM2548:155` is https://github.com/Charcoal-SE/Userscripts/blob/f6b7736/fdsc.user.js#L188 .

I've succeed to report another question after that, so it may only occurs for the first time (i.e. after authentication).

**Comment by ArtOfCode-** [comment]
I'm gonna close this for now, since it's now an old version of FDSC and hasn't been repro'd since. If anyone can repro, feel free to reopen or comment.

**Comment by angussidney** [comment]
@ArtOfCode- I have repro'd many times, however it doesn't seem to have any effect on functionality so I'll leave it closed
