### ISSUE TITLE
FDSC says "not autoflagged"

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/Userscripts#22]
Seems that recently, the FDSC additions in the flag dialog box will always display "not autoflagged", even if a post was in fact autoflagged.

So far, this is based on a measly two samples; obviously, this requires yet-undeleted autoflagged spam to actually repro. http://chat.stackexchange.com/transcript/message/34745503#34745503

**Comment by tripleee** [comment]
Maybe we could even piggyback in a request to display the spam weight of the post, if that's easily available?

**Comment by ArtOfCode-** [comment]
I'll take a look. Seems odd, though,and if there is something wrong it's probably metasmoke-side.
