### ISSUE TITLE
FDSC - Enable confirmation of your autoflag

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/userscripts#23]
When a post is autoflagged, using one of my flags, I'd like to be able to confirm it as a TP from FDSC. Right now, that's not possible, because I can't flag it again and the TPU- report is coupled to the Flag button.

**Comment by markyi370** [comment]
Can you retract an autoflag?

**Comment by Glorfindel83** [comment]
Yes, this should be possible (I haven't tried, though). After you retract a flag, you can't flag it again, so this is isn't a possible workaround.

**Comment by j-f1** [comment]
This could also be a feature AIM provides, so I’m adding it here.

**Comment by Glorfindel83** [comment]
I'm not sure if I like being able to confirm a post merely by seeing the Smokey report. For some obvious spam posts this works well (and I must admit I have done so myself), but I have seen some borderline cases (even ones which were autoflagged).
Note that this will require some authentication steps to get a personal MS write token from our users.

**Comment by angussidney** [comment]
Yeah @j-f1, we want people to actually look at the post before confirming their autoflagging. This is a FDSC thing.

**Comment by Cerbrus** [comment]
@angussidney / @j-f1: I think I've got this fixed ^
Review, please :-)
