### ISSUE TITLE
Make FDSC disable the flag option (or at least show) if it was autoflagged

### ISSUE THREAD

**Issue by markyi370** [Charcoal-SE/Userscripts#25]
In chat, M.A.R. pointed out that it is suboptimal to try to flag an autoflagged post.

http://chat.stackexchange.com/transcript/message/35062447#35062447

Proposition: gray out the box if you already autoflagged it.

**Comment by Undo1** [comment]
Probably more work than it's worth. Also, we need people to be able to retract autoflags if necessary.

**Comment by ArtOfCode-** [comment]
Good point about retracting flags; declining this.
