### ISSUE TITLE
Autoflagging info text is covered by chat controls on own autoflags

### ISSUE THREAD

**Issue by Mego** [Charcoal-SE/userscripts#34]
Own autoflag:

![image](https://cloud.githubusercontent.com/assets/853264/22778623/369e98de-ee7d-11e6-9e8d-f3dece91e479.png)

Other's autoflag:

![image](https://cloud.githubusercontent.com/assets/853264/22778613/2c5566aa-ee7d-11e6-9910-f4f4b5b45ff4.png)

This is not really a serious issue at all, but it would be nice to have the controls not cover up the text.

**Comment by j-f1** [comment]
@Mego The reason this is like this is because the autoflagging indicator is hidden by the popup menu, so I just put a copy in that popup.

**Comment by j-f1** [comment]
This was fixed by adding the “You autoflagged” indicator to the hover icons.
