### ISSUE TITLE
AIM isn't telling me whose flag was used

### ISSUE THREAD

**Issue by Mego** [Charcoal-SE/userscripts#35]
![image](https://cloud.githubusercontent.com/assets/853264/22933085/0841ed58-f290-11e6-848b-7f30d215c306.png)

I'm using latest Chrome, and the only other userscript affecting chat is PopcornSE.

**Comment by Undo1** [comment]
Looks like this is happening only when the data is received from the websocket.

**Comment by angussidney** [comment]
This issue is now occuring all the time, since we are casting more than one flag

**Comment by j-f1** [comment]
This should be fixed in v0.10-beta.1.
