### ISSUE TITLE
AIM: Flag symbol links to an undefined ID

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/userscripts#39]
When a new post comes through the websocket and AIM decorates the message with the appropriate symbol, it links to an undefined URL (e.g. `https://metasmoke.erwaysoftware.com/post/undefined/flag_logs`)

Note that this does not happen when autoflag info is fetched from the API.

Related issue: Only one autoflagging user is displayed on hover when info was retrieved from the websocket, but after reload, all flaggers are listed.

**Comment by j-f1** [comment]
Related issue is now fixed.
