### ISSUE TITLE
License all userscripts under dual Apache 2/MIT

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/userscripts#40]
We intend to license all Charcoal userscripts under the same license combination we use for Smokey: Apache 2.0 or MIT, at user's option. This requires the agreement of:

- [x] @angussidney 
- [x] @ArtOfCode-
- [x] @Cerbrus 
- [x] @ferrybig 
- [x] @Glorfindel83 
- [x] @Gothdo 
- [x] @honnza 
- [x] @j-f1 
- [x] @teward 
- [x] @Undo1 

If you agree to this licensing, please type or copy/paste the following statement into a comment on this issue:

> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by ArtOfCode-** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by Glorfindel83** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by j-f1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by ferrybig** [comment]
I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to choose either at their option, and impose no
additional or further terms or conditions on my agreement to this licensing.

Op 18 feb. 2017 14:28 schreef "J F" <notifications@github.com>:

I license past and future contributions under the dual MIT/Apache-2.0
license, allowing licensees to choose either at their option, and impose no
additional or further terms or conditions on my agreement to this licensing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Charcoal-SE/userscripts/issues/40#issuecomment-280845591>,
or mute the thread

**Comment by Cerbrus** [comment]
'Kay :-)

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by Undo1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by teward** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by honnza** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by angussidney** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.

**Comment by Gothdo** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option, and impose no additional or further terms or conditions on my agreement to this licensing.
