### ISSUE TITLE
Flag from Chat implementation

### ISSUE THREAD

**Issue by magisch** [Charcoal-SE/userscripts#43]
Based on a chat conversation starting [here](http://chat.stackexchange.com/transcript/message/35596300#35596300)

I propose new functionality for FDSC (or a new userscript that works like FDSC and does this) that:

1. Adds a button to Smokey reports in chat.
2. On clicking that button, pops a confirmation dialog (optional)
3. When confirmation is obtained, casts a spam flag against the post in the report, using the SE Api
4. Sends `tpu-` feedback to Metasmoke in the same way FDSC does.

Reason for this FR:

In an exceeding number of cases, the fact that a report is spam is super obvious even from the title and chat message. If a report trips 8 filters and starts with "Celesta Male Enhancement" there is no possible way that that report could possibly be a FP. Having a "Flag and feedback this from chat" button would be nice to save time and the work of opening an obvious spam post before flagging it.

Would have to be subject to caution, though.

Also helpful for those of us who don't want to visit certain SE sites (like gaming.SE) at work, if we had a button from chat (could still view the post on MS).

Some examples of reports for which this would be exceedingly useful
(Posts where you really don't need to open them to know they're spam):

> [ SmokeDetector | MS ] Bad keyword in body, bad keyword in title, link at end of body, pattern-matching website in body: Fall Skin Care Tips For Dry Skin by flahertyianae on drupal.SE

> [ SmokeDetector | MS ] Bad keyword in body, bad keyword in title, blacklisted website in body, link at end of body, pattern-matching website in body: The antiaging remedy properties of these substances by jakgafoyici on askubuntu.com (@ThomasWard)

> [ SmokeDetector | MS ] URL in title, bad keyword in body, bad keyword in title, pattern-matching website in body, pattern-matching website in title: quicksupplementfact.com/testo-ultra-es/ by eyemr kipa on apple.SE

**Comment by Cerbrus** [comment]
Case in point:

![capture](https://cloud.githubusercontent.com/assets/2911988/23205981/432d30a0-f8ec-11e6-80cd-956400a7d08c.PNG)

One doesn't need to open that to know that it's a TP. It'd be very convenient to be able to flag & feedback that at the press of a button (with confirmation to catch accidental clicks)

**Comment by ArtOfCode-** [comment]
I'm reluctant to do this. Yes, there is plenty of spam that can be solidly identified from the title alone. But, should anyone ever take objection to our work, we can still say "humans look at every post" - which may not be true with this implemented.

Open to discussion, though. Thoughts?

**Comment by magisch** [comment]
@ArtOfCode-  Humans do look at every post, even with this. Some human consciously decided after seeing information on a post to flag it as spam. Maybe you could implement this only working for posts hitting at least 150 score or something, although that'd complicate things. Maybe make this not available to absolutely everyone. 

Comes down to: Do you trust flaggers in this room to not misuse this?

**Comment by Cerbrus** [comment]
@ArtOfCode- @honnza had [an idea](http://chat.stackexchange.com/transcript/message/35596481#35596481) for that:

> _" add the post body into the confirmation dialog"_

**Comment by ArtOfCode-** [comment]
@magisch I trust Charcoal people, yes. I don't trust meta-type people. "But how can you tell if it's spam without looking at the post?! You're making decisions that could apply penalties to legitimate users because their title looked weird!!1!11!eleven" We know it ain't true, but it wouldn't take a veteran meta-lawyer to at least spread some concern.

@Cerbrus @honnza This idea, I like.

However it's done, this should probably be a new script rather than FDSC - FDSC is all about the flag dialog, so this might be scope creep.

**Comment by j-f1** [comment]
Maybe call it FIRE: Flag Instantly, Really, Electronically — that way there’s AIM & FIRE.

**Comment by ArtOfCode-** [comment]
Alternatively, you can have Flag Integrations for Relays Electronic

**Comment by Cerbrus** [comment]
Fairly Instant Reduction Effort

**Comment by ArtOfCode-** [comment]
For Immediately Removed Effluent

**Comment by j-f1** [comment]
We could also do what the people who invented UTC did:

> **Coordinated Universal Time** (French: *Temps universel coordonné*) [is] abbreviated to **UTC**
<sup>[source](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)</sup>

**Comment by angussidney** [comment]
I'm sorta against this for the same reasons as @ArtOfCode- - we don't want to be labelled as a flagging ring who flags without looking at things. 

If we do end up making a userscript to do this, at least require the post to reach the default autoflagging threshold 280.

**Comment by Undo1** [comment]
I'm also probably against doing this from chat, but I have considered sending manual flags from metasmoke. For me, a metasmoke pageload + 1 click is much faster than an SE pageload + 3 clicks to flag (or keyboard shortcuts, which I always get messed up on anyway).

**Comment by honnza** [comment]
The next step would be to display said metasmoke page in a pop-up rather
than a separate tab

**Comment by Cerbrus** [comment]
@Undo1 / @angussidney: Wouldn't those concerns be covered by:

> _"add the post body into the confirmation dialog"_ (https://github.com/Charcoal-SE/userscripts/issues/43#issuecomment-281635698)

**Comment by angussidney** [comment]
@Cerbrus Even still, for posts with lower weight, context is everything.

**Comment by Cerbrus** [comment]
This FR is more intended for the obvious spam that really doesn't require a page load, @angussidney.
So, if there could be a weight requirement before the button is available, that would pretty much cover the concerns here, I think.

**Comment by JC3** [comment]
Not that I have much say here, but I share the reluctance expressed above. No matter the intent, if the button is present, it *will* be pressed. So adding a weight threshold seems to mostly fix that.

That said it doesn't seem like there's a problem with having enough people to get rid of posts, does it? If you don't want to visit the site somebody else will probably get it, especially after that Smokey meta post attracting more people. It's been shown already (in that post) that deletion times are at record lows so it doesn't seem like there's real motivation for any added slightly-risky convenience.

**Comment by Cerbrus** [comment]
<sup>(First of all, I'm sorry if this comes across as aggressive. I'm a nice wolf, I'd just _really_ like this ;-) )</sup>

So, even if there's a weight restriction, _and_ the popup renders the reported Q/A, that still doesn't cover it?
There doesn't need to be _"something hurting the system"_ for a feature request to be valid. This isn't about getting rid of spam faster, this is just for the user's convenience.

_Open in a new tab_ -> _Open flag dialog_ -> _select "spam"_ -> <kbd>Enter</kbd> -> _Close tab_, or
_Open in a new tab_ -> <kbd>M</kbd><kbd>F</kbd><kbd>1</kbd><kbd>Enter</kbd> -> _Close tab_
Versus
_Open dialog with reported post_ -> _Select "accept"_ (/ _"reject"_ for false positives)

If people abuse this, it is _their SO accounts_ that will receive a flag ban.
As @angussidney [explained in chat](http://chat.stackexchange.com/transcript/message/35708707#35708707), invalidating all of a user's feedback is relatively trivial.

---

I was thinking of writing a separate userscript specifically for this feature, so it has a _separate API key_ which could also be revoked from MS's side.
A separate userscript would require implementing the parsing of smokey's messages _again_. As a workaround, I figured it might be possible to [allow separate userscript to register event handlers in AIM.](http://chat.stackexchange.com/rooms/11540/conversation/allow-separate-userscript-to-register-event-handlers-in-aim)  
This would mean the new userscript would only have to add the button, popup and related events, without having to worry about (_re-implement_) parsing SD reports, preventing code duplication. _However_, that would create a dependency on AIM, which opens yet another can of worms...

Altogether, I think we _can_ secure this enough.  
We could even limit it to **only be accessible after feedback has been provided** by someone. That way, you'll _always_ have user feedback before _anyone_ can use the "convenient flag" dialog.  
(That user feedback could still be a blind _"tpu-"_ from chat, but at least there's plenty of transparency there)

Sure, it takes some effort to implement, and sure, it's all just for convenience.

**Comment by JC3** [comment]
By the way, regardless of anything else, you'd *never* want to show such a button for answers, since they display the title of the question in the message, which is not the post in question.

**Comment by j-f1** [comment]
@Cerbrus You can just set a new attribute on `autoflagging.decorate`:

```js
/*!
 * “Spec” for methods of autoflagging.decorate:
 * Takes an element to update.
 * data is from the API.
 * Properties:
 * * location [required] ("before" | "after") Where to add the element if it
 *   doesn’t exist
 * * key [optional] The key that must be present on the data. The value of
 *   this key is passed as the second parameter.
 * * el [optional] the name of the element to create.
 */
```
<sup>[source](https://github.com/Charcoal-SE/userscripts/blob/fa5cba7aea0a0c26e058bb384e7c526966e8f8ad/autoflagging.user.js#L126-L136)</sup>

**Comment by magisch** [comment]
@Undo1 I'd very much like an implementation from MS too. Have a "Flag as spam" and a "Flag as Abusive" button show up on MS pages that aren't recorded deleted yet. Would save us from actually visiting the spam.

**Comment by ArtOfCode-** [comment]
@magisch That can be done; pretty easy, actually, since we already have write tokens.

**Comment by magisch** [comment]
@ArtOfCode-  This could actually be of tremendous use to people, for a few reasons:

- SE appends question titles to urls, so some people refrain from clicking questions "Alpha Testo Force ProX" or something to avoid having that in their browser history.  "metasmoke.erwaysoftware.com/posts/208584" is super innocous by comparison.

- Metasmoke frequently loads faster then SE does, especially when not using adblock, due to bouncing advertisements.

**Comment by Cerbrus** [comment]
@j-f1: I figured out how to "Extend" AIM, from your comment earlier, basically:

    autoflagging.decorate.fire = function ($fire, data) {

How can I tell if the reported post is a question or a answer, from `data`? (Aside from manually parsing the `link`'s contents)

**Comment by j-f1** [comment]
@Cerbrus There’s no way AFAIK. You could either post a feature-request on metasmoke or search for `/a/` in the link.

**Comment by ArtOfCode-** [comment]
metasmoke does it by looking for /a/ in the link, so you might as well do that in client-side code

**Comment by Cerbrus** [comment]
Yea, that's [what I'm doing now](https://github.com/Charcoal-SE/userscripts/commit/635d2ebe1ecf0c5f946cc0e8d5600f654af5c21e#diff-14d1937e50db00ce8b8d61963f407cffR124), @ArtOfCode-.

**Comment by Cerbrus** [comment]
Since [🔥 FIRE 🔥](https://github.com/Charcoal-SE/userscripts/tree/master/fire) has come alive, This issue can probably be closed, right?
