### ISSUE TITLE
AIM: live deletion information isn't always processed correctly

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/userscripts#49]
Sometimes (in ±5% of the cases), a deletion log from the websocket isn't processed correctly. Last days, I've seen it happen only for AskUbuntu posts, but I don't know if that has something to do with the issue.

**Comment by angussidney** [comment]
I wouldn't be surprised if something just errored out in transmission

**Comment by Glorfindel83** [comment]
I just saw a case where the websocket did send a deletion_log message for an AskUbuntu question, but it still wasn't greyed out by AIM.

**Comment by Glorfindel83** [comment]
The problem is that for AskUbuntu messages, *two* deletion logs are sent (within 50 milliseconds) instead of one. While this is probably something that @Undo1 or @ArtOfCode-  should fix in metasmoke, we can also use `addClass("ai-deleted")` instead of `toggleClass("ai-deleted")`.

**Comment by honnza** [comment]
why ... have you been using `toggleClass` instead of `addClass`?

**Comment by Glorfindel83** [comment]
IDK - I think [angus](https://github.com/Charcoal-SE/userscripts/commit/d81483efe2864d61d5f6c9206d25c269368f227a#diff-b95d7c4fb73e7f62ed420cd32dfbf65a) counted on the websocket message being sent only once.
