### ISSUE TITLE
AIM: live autoflag count is sometimes wrong.

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/userscripts#50]
Reported by [DavidPostill](http://chat.stackexchange.com/transcript/message/35674397#35674397) and I saw the problem at that moment as well. After reloading, the correct number of autoflags was shown. Either a websocket message was not received, or it wasn't processed correctly.

**Comment by j-f1** [comment]
Since it seems like this hasn’t been reproduced since then, I’m going to assume that it was a network hiccup.
