### ISSUE TITLE
AIM: live information is sometimes shown only after the first feedback is received

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/userscripts#51]
Sometimes, it happens that Smokey posts a new report, the spinner is shown (and no autoflag information) and the spinner disappears only after the first feedback is received. I suspect it's a timing issue, but I can't see what goes wrong.

**Comment by honnza** [comment]
Why did you raise this as three separate issues?

**Comment by Glorfindel83** [comment]
Because they might take different timeframes and/or authors to resolve.

**Comment by Glorfindel83** [comment]
@Undo1 @ArtOfCode- it seems that the websocket does not send `not_flagged` messages anymore. Could one of you have a look, please?

**Comment by Undo1** [comment]
Yep, metasmoke issue. Should be a simple fix.

**Comment by Undo1** [comment]
Fixed an issue causing us to not send the `not_flagged` messages. I did find another potential issue, though - the websocket message outran the chat post. I haven't seen that happen outside of this one test, but it's something to watch for.

Leaving this open until we can confirm it's fixed.

**Comment by Glorfindel83** [comment]
@Undo1 FYI, we noticed that as well and [JF built something to take care of it](https://github.com/Charcoal-SE/userscripts/blob/master/autoflagging.user.js#L388). It's really hard to test, though.
