### ISSUE TITLE
FIRE: Doesn't check autoflag before allowing feedback

### ISSUE THREAD

**Issue by DavidPostill** [Charcoal-SE/userscripts#57]
I autoflagged (without realising) this report https://m.erwaysoftware.com/posts/by-url?url=//superuser.com/questions/1185423.

When clicking tpu- in FIRE the flag failed (as expected - I had already autoflagged), however feedback was still sent to smokey ...

**Comment by honnza** [comment]
this might be considered a feature...

**Comment by Cerbrus** [comment]
Technically, this is a (Partially implemented) feature.

FIRE doesn't know if you've flagged a post or not. That's on the TODO list:
If you've already flagged the post, it _shouldn't_ attempt to flag, again. However, you can still send feedback in case you (auto)flagged it.

Right now it simply tries to flag a post, regardless of if you've flagged it, or not.
