### ISSUE TITLE
Automatically downvote posts from FIRE

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/userscripts#70]
When the user feeds back `k`, FIRE should downvote the post.

Feedback 👍  if you agree, 👎 if you disagree, 😕 if you think that *only* NAA posts should be downvoted, and 🎉 if you think that `naa` posts should also be downvoted.

**Comment by ArtOfCode-** [comment]
:confused - *only* NAA posts should be downvoted, not spam/abusive.

**Comment by Cerbrus** [comment]
I'm reluctant in adding votes:

This would require FIRE to display the current (live) vote count on a reported post, as well as keeping track of what you voted.

I can (optionally) prevent FIRE from closing the report popup for NAA feedback, so it's easier to open the post on it's site.

**Comment by Undo1** [comment]
I'm not seeing the benefit here. If it's spam, and Smokey catches it, it's already on the fast track to deletion and you'd just be burning votes. 

If it's not spam, it's either a false positive or NAA - neither of which really benefit from downvotes (except in relatively rare cases involving review, but this is unlikely to make a noticeable difference there).

**Comment by Cerbrus** [comment]
Considering the votes on this issue, I'm closing it.
