### ISSUE TITLE
Add error indicator to Fire

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/userscripts#78]
At the moment, Fire doesn't show any indication that there is a problem with your internet connection when pressing the fire icon, is just silence swallows this error. This is a problem when you are using Fire from a bad internet location, you click on the icon and it seems like nothing really happens.

Suggestion: Add error "Post failed to load" message to fire and show a "Loading is taking a bit too long" message when loading times exceed 100-300 ms

**Comment by Cerbrus** [comment]
I'm almost certainly not going to add timers to AJAX calls.
I can look into notifications for failed requests, eventually.

**Comment by ferrybig** [comment]
How to reproduce if your internet is stable:

1. Open Charcoal HQ
2. Open Google Chrome Debugger
3. Go to network
4. Set the connection to to Offline
5. Try to open a post using fire
6. Observe nothing happens
