### ISSUE TITLE
FIRE popup cut off in narrow windows

### ISSUE THREAD

**Issue by Cai333** [Charcoal-SE/userscripts#80]
Currently, the FIRE popup is positioned (with some JS added inline CSS) horizontally centered on the main chat (i.e. excluding the sidebar)...

If the window is too narrow the popup gets cut off, even if there's enough screen space to fit the popup... and the negative `left` value means resizing the browser doesn't help (without closing and reopening the popup).

Example:

![screenshot-2017-05-06-22 10 30](https://cloud.githubusercontent.com/assets/19490066/25776260/924854b8-32b1-11e7-8601-bd70ca55c655.jpg)

Personally I'd say the popup should just be aligned to the left anyway (the JS positioning logic could then be done away with and just done in the external stylesheet).

If the popup does have to be centered could we at least add a check to make sure the `left` value is non-negative (maybe just give it a reasonable minimum)?

**Comment by Cerbrus** [comment]
I'll see about limiting the `left` to be `>= 0`
