### ISSUE TITLE
Add the user’s rep to FIRE

### ISSUE THREAD

**Issue by j-f1** [Charcoal-SE/userscripts#81]
Currently, there is no way to tell if a post was made by a 1-rep user or a 20k-rep mod. It would be nice to show the user’s rep and mod status next to their username.

**Comment by Cerbrus** [comment]
For my own reference:

Line 1079

    const userName = d.username + (d.se && d.se.post ? ` <span>(${d.se.post.owner.reputation})</span> ` : ' ');

Line 1096

     _('span', 'fire-username', {html: userName, title: 'Username'})

Just gotta make that work if SE data loads slower than the time a report takes to open.
