### ISSUE TITLE
AIM: Change the way messages are expanded to cause less difficulty with FIRE's 🔥 button

### ISSUE THREAD

**Issue by spacemonaut** [Charcoal-SE/userscripts#86]
On two-line messages, the message-expansion behaviour makes it inordinately hard to hit FIRE's 🔥 button.

Currently it often takes a few attempts to position my cursor correctly. The current expansion behaviour means the 🔥 button slides up out of the way and the spam link is placed beneath my cursor instead. The mouse movement to place my cursor back over the tiny 🔥 button is usually just a bit too far, and re-collapses the message.

![fire](https://cloud.githubusercontent.com/assets/4585677/26351791/ee3692b0-3fb0-11e7-8b81-bc84f354ed3c.gif)  
<sup>(dramatic re-enactment: fairly accurate)</sup>

Ways to resolve this could be:

* make the message instead overlap below messages when it expands, so that it's not affecting page flow or pushing anything upwards.
* wait a second before a message collapses, rather than doing so instantly upon mouse leave, so that I can reposition my cursor back inside the message before it collapses.

**Comment by ferrybig** [comment]
Fire isn't responsible for this expansion of messages, it is our Autoflagging Information & More (AIM) script that does this.

**Comment by jdahobbs** [comment]
Thanks for clarifying. I've retitled. Does that seem appropriate?

**Comment by Cerbrus** [comment]
What browser is this?
Chrome keep the top of the element in place, and makes it expand down...

**Comment by jdahobbs** [comment]
This is in Chrome on Windows.

If I'm scrolled up to any degree in the backlog, the top of the element will remain in place & the message will expand downwards, just as you describe.

If I'm scrolled to the bottom of the backlog, the message will expand upwards. (It might not do this for the very first mouseover, but it will for other ones.)

**Comment by ArtOfCode-** [comment]
It's because of chat trying to keep you at the bottom if you're already at the bottom. Not sure how to fix that, though I've noticed it too.

**Comment by Videonauth** [comment]
Happen to very badly on Firefox, makes hitting the FIRE icon very difficult sometimes.

**Comment by makyen** [comment]
This should be resolved with AIM version 0.31.
