### ISSUE TITLE
FIRE: After getting an API token, whole of screen remains blurred

### ISSUE THREAD

**Issue by doppeldeveloper** [Charcoal-SE/userscripts#87]
I've noticed the following bug: when I initially authorize FIRE by giving it an API token from metasmoke, the following happens:

* the main FIRE dialog will close
* a message will appear in the top right confirming that FIRE's been set up with API access for feedback
* **the blur overlay does not disappear**

This means after I initialise FIRE I need to reload the page.

Naturally this doesn't happen often, so I don't think this is very severe.

I'm using Chrome 58 on Windows 10.

**Comment by CalvT** [comment]
I think this is a "bug by design" to make you reload the page so that FIRE loads properly with the token

**Comment by Cerbrus** [comment]
Nah, not by design. FIRE doesn't need a reload. If it did, I'd have _made_ it reload.

I'll look into it tomorrow...

**Comment by izwick-schachter** [comment]
My PR should have resolved this. Is the issue still happening?

**Comment by angussidney** [comment]
@izwick-schachter Just tested, it works. I assumed that by merging the PR the issue should have been closed automatically, but obviously that wasn't the case. Anyway, thanks for fixing that up!
