### ISSUE TITLE
FIRE can't properly authenticate with metasmoke

### ISSUE THREAD

**Issue by izwick-schachter** [Charcoal-SE/userscripts#91]
Upon installing FIRE on a new machine, it prompted me for write permission from the metasmoke API. I clicked on request token, it took me to a new window and gave me a code to pass back to FIRE. The input field in FIRE only permits 7 characters (via a `maxlength="7"` attribute). When I lengthened it to 8, clicking "save" ceased to do anything.

Screenshots:

![screen shot 2017-07-22 at 9 57 48 am](https://user-images.githubusercontent.com/15304293/28491852-bdc478b0-6ec5-11e7-89b0-66c5f218ff1d.png)

![screen shot 2017-07-22 at 9 57 37 am](https://user-images.githubusercontent.com/15304293/28491829-86914c10-6ec5-11e7-916d-777653eeb16e.png)

**Comment by angussidney** [comment]
Appears to have been fixed by the PR.
