### ISSUE TITLE
FIRE: Randomly stops working with "TypeError: fire.chatUser is undefined" errors

### ISSUE THREAD

**Issue by DavidPostill** [Charcoal-SE/userscripts#94]
Windows 7 Home Premium 64 bit, Firefox 54.0.1

Clicking the FIRE icon doesn't work (no dialog is displayed).

The following error is generated if I hover over or click on the FIRE icon.

`"TypeError: fire.chatUser is undefined"`

This can sometimes (but not always) be fixed with a reload or restart of Firefox.

**Comment by angussidney** [comment]
Repro'd, also on Firefox 54.0.1 64bit on Windows 10 Education 64bit.

**Comment by angussidney** [comment]
Fixed in 50bdd4c by @Cerbrus
