### ISSUE TITLE
SDS not displaying status of Smokey instances

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/userscripts#95]
This stopped working a while ago, presumably due to the MS websocket changes. SDS is simply displaying a Smokey icon and nothing else. Screenshot:

![sds](https://user-images.githubusercontent.com/4848802/29408362-3a7b1f2e-838b-11e7-899b-e9b09d5ed008.PNG)

I've tried hovering, clicking, etc, but nothing is happening.

Firefox 54.0.1, Win 10, SDS 0.0.6 (latest)

**Comment by j-f1** [comment]
Can you run `localStorage.debug = 'sds*'` and copy/paste the logs here?

**Comment by angussidney** [comment]
Reinstall fixed issue
