### ISSUE TITLE
Opening FIRE causes the chat sidebar to disappear

### ISSUE THREAD

**Issue by ArtOfCode-** [Charcoal-SE/userscripts#98]
...yeah. Weird.

[![FIRE bug](https://user-images.githubusercontent.com/10406565/33800806-407de71c-dd40-11e7-8980-ef8f89ff4e81.png)](https://user-images.githubusercontent.com/10406565/33800806-407de71c-dd40-11e7-8980-ef8f89ff4e81.png)

Using Firefox 57.0.2 on Windows, userscript manager is Violent Monkey.

The sidebar is present before I open FIRE, and returns once I've closed it.

No errors in the console, one warning that may or may not be from FIRE:

`Use of Mutation Events is deprecated. Use MutationObserver instead.     
[jquery.min.js:3:9644]`

**Comment by j-f1** [comment]
I’m not a FIRE maintainer and I don’t have FF 57 or Windows, so I’m not really the person who should go about fixing this IMO.

**Comment by ArtOfCode-** [comment]
Huh, I thought you were. My bad :)

**Comment by Cerbrus** [comment]
Looks like the `#sidebar` is, for some reason, losing its `fixed` positioning. When FIRE is opened, it jumps up to the top of the page.

I can't look into it too much, but tbh, this looks like a FireFox bug...?

**Comment by ArtOfCode-** [comment]
I woudn't be surprised...

**Comment by makyen** [comment]
Resolved in FIRE version 1.4.0, PR #180.
